name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone deriv-app Repository
        uses: actions/checkout@v4
        with:
          repository: 'binary-com/deriv-app'
          path: 'deriv-app'
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      # - name: Install Dependencies
      #   run: npm install
      #   working-directory: ./deriv-app

      # - name: Run Bootstrap
      #   run: npm run bootstrap
      #   working-directory: ./deriv-app

      # - name: Build All Packages
      #   env:
      #     NODE_ENV: production
      #   run: npm run build:all
      #   shell: bash
      #   working-directory: ./deriv-app

      # - name: Analyze Build
      #   run: npm run analyze
      #   working-directory: ./deriv-app

      - name: Run Compile Script
        run: node compile.js
        working-directory: ${{ github.workspace }}

      - name: Setup Git Config
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Commit and Push Changes
        run: |
          mv dist static/2024-04-25

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: static
          clean: false
